### ISSUE TITLE
Cuutruyen Extension URL change report 

### ISSUE THREAD

**Issue by dangtiendongdong** [beerpiss/tachiyomi-unofficial-extensions#11]
### Source information

Cuutruyen

### Source language

Vietnamese

### Source new URL

https://nettrom.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
Change domain in extension settings.
