### ISSUE TITLE
Colamanga

### ISSUE THREAD

**Issue by ghyeng** [beerpiss/tachiyomi-unofficial-extensions#5]
### Source information

Colamanga

### Source language

Chinese

### Source new URL

https://www.colamanga.com/

### Other details

The source's domain has changed and the extension is no longer working.
Sorry for duplicate issue but previously opened issue on this was auto closed by bot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
Updated base URL in [`d4b2da7`](https://github.com/beerpiss/tachiyomi-unofficial-extensions/commit/d4b2da785b2815cd67840da69daa6fad7f77f7fb).

No idea if the extension works though, I've been busy and can't tend to these things for now. Reopen if it doesn't.

**Comment by NeKoOuO** [comment]
Where can I get the Cola's extension? Is this unofficial? I can't find it in the app

**Comment by beerpiss** [comment]
> Where can I get the Cola's extension? Is this unofficial? I can't find it in the app

...how did you even get here without once reading the word **unofficial** once? it's literally in the repo name.

https://beerpiss.github.io/tachiyomi-unofficial-extensions

**Comment by NeKoOuO** [comment]
>sorry I'm blind...😔
